server:
  port: 8721

service-url:
  user-service: http://localhost:8301

spring:
  cloud:
    gateway:
      routes:
        - id: path_route #\u8DEF\u7531\u7684ID
          uri: ${service-url.user-service}/user/{id} #\u5339\u914D\u540E\u8DEF\u7531\u5730\u5740
          predicates: # \u65AD\u8A00\uFF0C\u8DEF\u5F84\u76F8\u5339\u914D\u7684\u8FDB\u884C\u8DEF\u7531
            - Path=/user/{id}
