server:
  port: 8305

spring:
  application:
    name: hystrix-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 注册服务，为了避免注册失败，尽量添加多个实例
      defaultZone: http://localhost:8201/eureka/

service-url:
  user-service: http://ribbon-service

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream #暴露hystrix监控端点
