server:
  port: 8201

spring:
  application:
    name: eureka-server

eureka:
#  instance:
#    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false
